### ISSUE TITLE
#195 Component cannot be deleted when properties tab is open

### ISSUE THREAD

**Issue by pattrickx** [Flutter-Vision/FluterVision#160]

**Comment by mateuslimax22** [comment]
Fixed on fix/#129

**Comment by brunoamuniz** [comment]
i still have issues deleting components specially when they are nested inside others
